spring.application.name=rest-api

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=sps_data

server.port=8081

mqtt.broker=tcp://sr-labor.ddns.net:1883
mqtt.username=pablo.deges@stud.hs-bochum.de
mqtt.password=018365939
mqtt.client-id=rest-api-publisher